# .github/workflows/CI_Build.yml

name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.6  # Specify the required Terraform version

      # Terraform Init
      - name: Terraform Initialization
        working-directory: ./k8s-terraform
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Run Terraform Plan
        id: plan
        working-directory: ./k8s-terraform
        run: terraform plan -out=tfplan
        env:
          TF_LOG: INFO
          TF_INPUT: false

      # Apply Terraform configuration if on main branch or if approved
      - name: Run Terraform Apply
        working-directory: ./k8s-terraform
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          TF_LOG: INFO
          TF_INPUT: false

      # Output URLs for services (optional)
      - name: Output Service URLs
        run: |
          echo "Producer Service URL: $(terraform output -raw producer_service_url)"
          echo "Kafka Service URL: $(terraform output -raw kafka_service_url)"
          echo "Zookeeper Service URL: $(terraform output -raw zookeeper_service_url)"
          echo "Kafdrop Service URL: $(terraform output -raw kafdrop_service_url)"
